### ISSUE TITLE
PeeringDB IRR object source registry parsing

### ISSUE THREAD

**Issue by ggiesen** [peering-manager/peering-manager#168]
### Environment
    Python version: 3.6.6
    Peering Manager version: 0.99-dev

### Proposed Functionality
Ability to parse out source database from PeeringDB.

Many networks add a source registry prefix to their IRR objects in the 'IRR as-set/route-set' field in PeeringDB, causing bgpq3 to fail when generating router configurations.

While this can be solved by manually editing the peer (and disabling sync with PeeringDB for AS-SET), it's time-consuming for a large number of peers (especially if they are imported in an automated fashion).

When an AS-SET is preceded by TEXT followed by two colons (::), strip the TEXT and do one of the following:
a. Instruct bgpq3 to directly query that source DB; or
b. Ignore the tag

### Use Case
Support IRR objects for peers that have the source registry prefixed to the IRR object

**Comment by ggiesen** [comment]
Updated request to remove references to multiple object support (which does indeed appear to be supported as long as there doesn't also exist the problem of having the source registry tag.

**Comment by respawner** [comment]
Do you have an example to provide me to reproduce the issue?

As far as I knew the code already supported parsing source registries for AS-SETs (with `::`). It even supposed to work when multiple AS-SETs are provided within the value. I've tested this with the HE.net AS-SETs.

**Comment by gmazoyer** [comment]
Closing as it appears outdated.
