### ISSUE TITLE
IX-API integration

### ISSUE THREAD

**Issue by netravnen** [peering-manager/peering-manager#174]
**Is your feature request related to a problem? Please describe.**

Operational automation support. 

- Going public with EPF in Tallinn, Latvia, Sep 17, 2019.
- Homepage: https://ix-api.net/

> Edited out screenshot for better readability

**Comment by netravnen** [comment]
Website live now

**Comment by respawner** [comment]
Looks like something really interesting it worth the shot looking into it. Maybe not for 1.0 but definitely for a next major release.

**Comment by respawner** [comment]
Going forward with this we should clearly define what's possible to do with IX-API and define workflows so each tool can benefit from the other. It's without a doubt something that worth investigating.

Lets grab the sandbox and all public available details for us to know what we can do with it and start playing. If anyone is interested in bringing this integration and have some clues about it, feel free to discuss in this issue.

**Comment by gmazoyer** [comment]
This feature is now a requirement for v2.0.

First step will be to implement details from available IX-API instances. In the second step will try make peering manager communicate with IX-API to order new services.

This issue will be blocked until #246 to be resolved.
