### ISSUE TITLE
Possibility to disable a whole IXP

### ISSUE THREAD

**Issue by MrXermon** [peering-manager/peering-manager#205]
### Environment
* Python version:  Python 3.6.8
* Peering Manager version:  v1.1.1-dev

### Proposed Functionality
It would be great if we could disable a whole IXP for example during maintenance. We currently connect to the router and deactivate the sessions/the group of sessions by hand but having this option from within peering Manager would be great!

### Use Case
If an IXP shuts down ports during maintenance it would be good to deactivate the sessions first.

**Comment by respawner** [comment]
I think that we should address this as part of #246 and be able to disable on connection to an IX (or several).

**Comment by gmazoyer** [comment]
This is no longer block as connection model is now merged.

**Comment by jamesditrapani** [comment]
Closing, all further communication regarding this request will be done via #292.
