### ISSUE TITLE
Associate InternetExchange with ixlan.id rather than network_ixlan.id

### ISSUE THREAD

**Issue by mngan** [peering-manager/peering-manager#216]
### Environment
* Python version:  3.6.9
* Peering Manager version:  master

### Proposed Functionality
Rather than use the network_ixlan.id to link the InternetExchange object to PeeringDB, can you not just use the ixlan.id? It doesn't appear that peering-manager is using this link for anything other than pulling the prefixes for the peering lan.

### Use Case
Admittedly we are an edge case. We are active on an IX, but for "reasons", we cannot have an entry in PeeringDB for our connection. The IX entries are being enforced by IX API. Without a valid peeringdb_id, I cannot scan a router for existing sessions since peering-manager doesn't know which prefixes to use. If peering-manager used the ixlan.id, then it would have access to the prefixes regardless of the status of our connection in PeeringDB. I can understand why you might want to also associate the network_ixlan.id, but in our case it would be better if peering-manager didn't have to rely on that. I was able to get around this by entering in someone else's network_ixlan.id, but that is an egregious hack. 

Also, a side note. The hint for the PeeringDB ID field says it can be empty. That is a incorrect, it must be 0 if you aren't using it. Also, the link to the instructions on how to find your PeeringDB ID goes to a non-existent page. 

### External Dependencies
None

**Comment by respawner** [comment]
Closed by a2c3de4.
