### ISSUE TITLE
External datasources

### ISSUE THREAD

**Issue by lspgn** [peering-manager/peering-manager#238]
### Environment
* Python version:  3.7.7
* Peering Manager version:  1.1.0

Hello @respawner,
Thanks a lot for Peering-Manager.

I am looking into deploying it internally but we have many databases already handling specific "tables" router names for instance.
I'm not familiar with Django, but I tried to have a new database engine that would feed off a HTTP JSON file until I realized Django only supports SQL.

Is there a way of using an external source without disrupting too much code in the model?

Or is my best best to copy the data an import it into the db?

Thank you

**Comment by respawner** [comment]
Hello @lspgn,

First of all thanks for your interest in Peering Manager :)

If we can avoid you to duplicate the data you have internally we can try.
We all know that having a unique source of truth is better that having many.

Anyway, as Django only support SQL database engine, maybe we can try integrating some kind of engine as a dedicated app inside Peering Manager itself. This means that the code taking care of the HTTP/JSON streams will be itself isolated (as much as possible) from the existing code.

That's a lot of work but I guess it worth the shot.

**Comment by jamesditrapani** [comment]
@lspgn Touching base to see if you ever ended up getting Peering Manager operational?

**Comment by lspgn** [comment]
@jamesditrapani yes and it worked well

**Comment by jamesditrapani** [comment]
> 
> 
> @jamesditrapani yes and it worked well

Thanks @lspgn. How did you solve the duplicate data challenge? Did you end up writing some form of hook?

**Comment by lspgn** [comment]
@jamesditrapani (sorry for the delay, i missed the notification)

There was a periodic script that was populating the data into Peering Manager from other sources, as long as a key (eg: router IP, ASN...) was be found, entry was just updated. If not, entry was created.
