### ISSUE TITLE
SSL error when connecting to Netbox inventory

### ISSUE THREAD

**Issue by mmarin11** [peering-manager/peering-manager#276]
Hi peering-manager team. I'm trying to configure Netbox as a source for routers but it looks that when peering-managers tries to connect to the netbox server it has a problem with the self signed certificate installed in the netbox server. Is it possible to configure the http request to ignore certificate errors?

Thank you

![image](https://user-images.githubusercontent.com/40378669/91135354-3c8d3e00-e66b-11ea-9deb-7a115e5953dc.png)

**Comment by respawner** [comment]
According to a `pynetbox` [PR](https://github.com/digitalocean/pynetbox/pull/252), this should be fixable by using a custom `requests`' session. A new optional setting like `NETBOX_VERIFY_SSL` (defaulting it to `True`) could be added to trigger the using of said custom session.

**Comment by mmarin11** [comment]
Hi. Thanks for prompt reply

I upgraded and tried adding the following options to the configuration.py file and restarted gunicorn and the web server. However I keep getting the same error when I try to add a router.

Is there something missing in the configuration file?


NETBOX_API_VERIFY_SSL=False


![image](https://user-images.githubusercontent.com/40378669/91210297-3b3f2e00-e6ca-11ea-8038-9a3dbf03a14a.png)

![image](https://user-images.githubusercontent.com/40378669/91210399-66298200-e6ca-11ea-9f9d-a801e6a9bd22.png)

**Comment by respawner** [comment]
This looks like requests is ignoring what we told us to do, aka do not verify SSL certificates. Running with the debug mode turned on may give some more clues about what is going on.

**Comment by mmarin11** [comment]
Hi Guillaume

When I add the option **DEBUG=True** in configuration.py in order to view additional details to the api connection to Netbox, I get t he following error. I'm not sure if this the correct way of enabling the debug option

Thanks for your support


![image](https://user-images.githubusercontent.com/40378669/91249479-3acb8500-e714-11ea-817c-76b77c2138dd.png)
