### ISSUE TITLE
Way to figure out prefixes that was grabbed for ASn

### ISSUE THREAD

**Issue by mirackle-spb** [peering-manager/peering-manager#280]
### Environment
* Python version:  3.6.9
* Peering Manager version:  1.2.1-dev

### Proposed Functionality
Need feature that can help to find out prefixes grabbed for specific AS-SET.

### Use Case
I have customer with AS-SET X. That X contains prefix Y.
But Y does dot appear in configuration.
Manual execution of bgpq shows me that prefix Y.
How to figure out why peering-manager does not import that prefix?
How to look on prefixes that already imported for specific ASn?

**Comment by respawner** [comment]
There is nothing specific done by Peering Manager here. It just take care of using `bgpq3` for you with defined arguments, tells it to return data as JSON and store the result as is. If you have a difference between what Peering Manager knows about prefixes for an ASN and what you see when manually executing the `bgpq3` command by yourself then it means that the two commands are different.

I was unable to reproduce this issue by using the exact same two commands (by PM and by hand). If you have some steps to reproduce this issue, you can provide them here and re-open the issue.
