### ISSUE TITLE
Any interest in adding Prometheus endpoint?

### ISSUE THREAD

**Issue by dgjustice** [peering-manager/peering-manager#286]
### Environment
* Python version:  yes
* Peering Manager version: yes 

### Proposed Functionality

`/metrics` endpoint provided by `django-prometheus` with a config flag

### Use Case

We have peering-manager deployed at ~Packet~ Equinix, and we track apps through Prometheus.  Would you be interested in a PR with a config switch to enable this in peering-manager?  Netbox does the same thing via `METRICS_ENABLED`.  It's a trivial change, but I'm open to input before I go hacking on it.  😄 

### External Dependencies

[`django-prometheus`](https://github.com/korfuri/django-prometheus)

**Comment by respawner** [comment]
Feel free to proceed 👍🏻
