### ISSUE TITLE
Custom fields or config context on Peering Manager routers

### ISSUE THREAD

**Issue by falz** [peering-manager/peering-manager#287]
### Environment
* Python version:  3.x 
* Peering Manager version: 1.2.

### Proposed Functionality
Ability to add arbitrary data for a router in peering-manager that can be used in a configuration template.

### Use Case
We currently use BGP region coding and hence auto generate per-region (per device) unique BGP communities. This does not currently seem possible in Peering Manager as there's no way to pass additional data to jinja.

In our use case, we have a 3 digit numeric code. The most basic functionality, which is an arbitrary custom field would work fine. We would use functions in Jinja to split it up properly. '

For those unaware of this style of config, we use is a tic-tac-toe board covering our region, where each area of this is a number, 1-9. the 2nd and 3rd digits is an arbitrary code for the device in that region, so 1-99. This is fairly common.

Even better however, would be either of these, my preference in this order

1. Pass the configuration context from Netbox to Peering Manager
2. have a local configuration context field, mirroring exactly what Netbox does - arbitrary Json.

There are probably other uses for this as well, but this would satisfy our needs and appears to be the only thing preventing us from using Peering manager in production.

An example of 'configuration context' in netbox would be just json, our use case would be something like:
```
{
    "autocommunity": {
        "popcode": "06",
        "region": "8"
    }
 }
```

**Comment by jamesditrapani** [comment]
@respawner Could we allow the user to add a new field type to the `Router` model from the UI, similar to https://stackoverflow.com/a/34907395/11588748 ?

**Comment by ggidofalvy-tc** [comment]
+1, I'd be really happy to see even an additional simple JSONField on the router and policy models. For the policy models, the use-case would be something like a list of prefixes to de-preference, applicable for a specific BGP session / (type).

**Comment by gmazoyer** [comment]
Lets add a new JSON field to routing policies and routers for now. If we were to bring custom fields, I'd like to make them available globally to any models in the code base.

**Comment by jamesditrapani** [comment]
Somewhat similar request in #97
