### ISSUE TITLE
Session enable/disable from Router, IX, BGP Group

### ISSUE THREAD

**Issue by mngan** [peering-manager/peering-manager#292]
### Proposed Functionality

It would also be nice to be able to disable all BGP sessions for a router, IX or BGP Group when taking a router or link down for maintenance. Doing it at the session level is too cumbersome if you have a lot of sessions, and you may disabled an individual session for some other reason, and you will lose that state if you flip all the sessions off and on. 

### Use Case

Router maintenance - you want to disable all the BGP sessions for all IX and direct sessions
IX Maintenance - disable all BGP sessions for all a specific IX
Link Maintenance - disable BGP for a particular peer on a particular router

When generating the templates the state for a session group be precalculated based upon the hierarchy of control, so you don't have to check through multiple objects to figure this out.

**Comment by falz** [comment]
Perhaps there should be more options than just binary enable/disable. For example, you may wish to send the GRACEFUL_SHUTDOWN community prior to maintenance, see:

* https://tools.ietf.org/html/rfc8326 

This effectively tells peers to set lpref to 0 internally. After that you may wish to disable them.

A similar affect could be achieved by a group policy change to reject all prefixes in and out while traffic drains prior to peer shut down.

Additional food for thought is support for BGP administrative shutdown communication, although I'm unsure which vendors support this currently.

* https://tools.ietf.org/html/rfc8203

**Comment by mngan** [comment]
So 3 states, `enable`, `disable`, `shutdown`? That seems sensible. How the shutdown/disable is implemented is up to the person constructing the templates. But definitely an example of how to use these flags should be added to the documentation.

**Comment by falz** [comment]
some states that seem to make sense to me would be:

* `enable` - default running peer
* `drain` or `depref` or `maintenance` or `??` - what I'm talking about - leave peer up but change its routing policies in some way, hopefully configurable via template
* `shutdown` or `disable` - actually administratively disable peer or remove it from config. unsure if all routers support disabling peers, IOS does but Junos doesn't for example. 

I'm not yet a user of peering-manager (I cannot use without https://github.com/peering-manager/peering-manager/issues/287 support) so I don't know if this type of thing already exists on a per-peer basis or not, and this request is extending it to a group?

If not, it seems like it should be flexible and each group or peer or even 'all peers on device X' would be the most useful way to implement.

**Comment by mngan** [comment]
Currently, you can enable/disable individual sessions. How that is implemented is up to you. So on Juniper, I deactivate the session which will shutdown the session. You could achieve the proposed functionality if you manually apply a policy or a tag to a BGP Group, IX or Router, and in your template you generate the appropriate configuration to perform that action based upon the policies/tags, but it is obscure and not easily understood/discovered how to do it. 

I only use the tags/policies for our own internal traffic management, but for something that everyone should be able to use, a more explicit system would be better.

**Comment by mngan** [comment]
Thinking about this in relation to the Jinja filter work, if there is a common state that can be specified at the router, IX/connection, BGP Group or session level, then it would be nice to have filter that given a session, figure out what its inherited state is. Similar to the idea of the filter for gathering policies. 

Then you could do something like:

```
{% set state = session | state %}
{% if state == 'enabled' %}
...
{% elif state == 'disabled' %}
...
{% elif state == 'maintenance' %}
...
{% endif %}
```
Otherwise you have to track the state of all the objects in the hierarchy in your template  to determine what state the session should be in.

**Comment by gmazoyer** [comment]
I'd like to implement this enhancement in order to move forward with other stuff. What do you people think we should do?

1. Remove the `enabled` field and add a `status` field with possible choices such as `enabled`, `shutdown`, `maintenance`, …
2. Keep the `enabled` field but also add a `status` field with possible choices such as `shutdown`, `maintenance`, …

I personally would be in favour of choice 1 to avoid any confusion in users minds.

**Comment by falz** [comment]
Item 1 seems most clean and the least confusing overall. 

Note: I say that as someone not yet using this in production and hence would have little impact of such change.

**Comment by wtremmel** [comment]
Also in favor for option 1

**Comment by gmazoyer** [comment]
> Note: I say that as someone not yet using this in production and hence would have little impact of such change.

To avoid any issues (with templating mostly) we will still expose a `enabled` property that will just be a proxy to `status == enabled` until we actually remove that proxy in 2.0 (I guess)

**Comment by mngan** [comment]
i agree with option 1 but leaving an enabled property.

**Comment by mngan** [comment]
one thing i realized while reorganizing my templates to deal with the status field of the router and the new connection object was that `disabled` on a router doesn’t mean the same thing as disabled on a session.

 on a router we view `disabled` as a flag to say don’t push configs automatically, but can be pushed manually.

`maintenance` still allows the automated config push but it shuts down all the sessions or stops accepting/advertising prefixes. 

this would have an effect on how a state filter might work if it evaluated all the parent objects.  

not sure how other people use these states.
