### ISSUE TITLE
Add a maxpref column in the peering sessions tabs (direct and ix), and a pdb-provided maxpref value

### ISSUE THREAD

**Issue by ynbrthr** [peering-manager/peering-manager#300]
Retrieve the configured maxpref on  a given bgp session, as well as the value maintained by networks in PeeringDB.

**Comment by jamesditrapani** [comment]
@ynbrthr You can retrieve the IPv4 & IPv6 max prefixes set in PeeringDB for ASNs in the PeeringDB data cache. For a session attached to an Internet Exchange this is located at `session.ixp_connection.peeringdb_netixlan.net.info_prefixes4` and `session.ixp_connection.peeringdb_netixlan.net.info_prefixes6`. Granted, these are fairly deep into the hierachy so maybe we could encompass these in the ASN model (with a default inheritage from PeeringDB if present)

**Comment by jamesditrapani** [comment]
We provide a PDB sync'd (if user selected) IPv4 & IPv6 max prefixes colum on an ASN. Not sure you'd want to customise this on a per session basis. @gmazoyer At this stage I would class this as wontfix, whats your opinion?

**Comment by gmazoyer** [comment]
We cannot really retrieve what's configured on a router right now as we don't parse configuration installed on devices. We can only assume it when generating the config and see the diff before committing them.
