### ISSUE TITLE
Bulk edit removes routing policies from IX sessions

### ISSUE THREAD

**Issue by 2bithacker** [peering-manager/peering-manager#309]
### Environment
* Python version:  3.6
* Peering Manager version:  v1.2.2-dev (6f3d669c363e9898437f5da34fc917db672557c3)

### Steps to Reproduce

1. Select multiple IX peering sessions that have routing policies set, click "Edit Selected"
2. Make a change to something, such as adding a comment. Do not select "Set null" for the routing policies.
3. Click "Apply"

### Expected Behavior

I expect the routing policies on the sessions to remain intact and unchanged, as I did not select "Set null" or select any policies to be added.

### Observed Behavior

The routing policies on the selected sessions are removed, leaving the policies empty.

**Comment by respawner** [comment]
Seems to be fixed (somehow) in master.
