### ISSUE TITLE
Run check_for_ix_peering_sessions command automatically

### ISSUE THREAD

**Issue by rlanyi** [peering-manager/peering-manager#311]
### Environment
* Python version:  3.9.0
* Peering Manager version: cda6b6142c75 (v1.2.1)

### Proposed Functionality
Run `python manage.py check_for_ix_peering_sessions` or equivalent when adding a new AS or when adding/deleting IX Peering Sessions to an AS on the GUI

### Use Case
When working with Autonomous Systems, for example adding a new one, Available sessions are not calculated automatically. You don't even see the tab until you run `python manage.py check_for_ix_peering_sessions`. After you run this and add one or more sessions from the list, they will appear on the IX Peering Sessions tab (that is correct), but they won't disappear from the Available Sessions tab (unless you've added all from the list which will make the whole tab to disappear).

As a workaround one could run the command above via cron every minute. The command finishes in a few seconds (at least with a few dozens of IXPs and AS numbers). But this wouldn't be a user friendly solution because it doesn't make it clear to the user why and when new sessions appear/disappear in the Available Sessions tab.

As an extra this would remove some confusion about how automatic handling of available IX peering sessions work and it would possibly solve the following issues as well:
- https://github.com/peering-manager/peering-manager/issues/219: the functionality is there, it is just invisible if one doesn't run the command above
- https://github.com/peering-manager/peering-manager/issues/299: same
- https://github.com/peering-manager/peering-manager/issues/91: this was probably solved after the user added all available sessions from the list and not just a few

### External Dependencies
There are no external dependencies.

**Comment by mngan** [comment]
I think that my [PR#305](https://github.com/peering-manager/peering-manager/pull/305) might solve this

**Comment by rlanyi** [comment]
@mngan thanks, I haven't seen this PR before. I think it would help when we add a new AS but wouldn't refresh the list of Available sessions when IX peering sessions are added/deleted. Would it be possible to do the same after addition/deletion as well?

**Comment by respawner** [comment]
This command will be (at some point) moved to a Redis task allowing event based trigger. So we can imagine adding a new AS and ask Redis to run a task updating the list of possible sessions.

**Comment by rlanyi** [comment]
To add more info, it seems that if you select only 1 IXP on the Available sessions tab, and that IXP has only 1 session (IPv4 OR IPv6) then the next page will contain only one session form and after importing it the IXP will disappear from the Available Sessions tab. But if the selected IXP contained both IPv4 AND IPv6 sessions, or you selected multiple IXPs (so in both cases, the result is multiple session forms on the Internet Exchange Peering Session Import page), they won't disappear after import.

So it seems that the intention was for this to work without the need for the console command (at least in case of session creation/deletion, I'm not sure about AS creation). Since the behavior is different depending on the number of created sessions I'd suggest to mark this as a bug.

**Comment by jamesditrapani** [comment]
@gmazoyer Confirming this was moved to a Redis job?

**Comment by gmazoyer** [comment]
This has been completely removed as there is no longer a need to look for IX peering sessions. They are discovered on the fly while reviewing AS details.
