### ISSUE TITLE
Load more data from PeeringDB

### ISSUE THREAD

**Issue by rlanyi** [peering-manager/peering-manager#314]
### Proposed Functionality

It would be great if more fields from PeeringDB would be shown in Internet Exchange / Available Peers like:
- all fields from Peering Policy Information (currently my top priority would be the General Policy field)
- some more fields from the AS Details (like Traffic Levels, Traffic Ratios etc.)

These values should also appear in the filter on the right.

### Use Case

When checking the list of possible peering partners in an IX it would be great to see more details of them at a glance. For example I'd like to filter to Open+Selective policy, indirectly excluding Restrictive ones.

**Comment by respawner** [comment]
This is actually part of a bigger rewrite that needs to be done: refactoring the PeeringDB code inside PM. It currently uses a custom sync method, but we should consider using the Python binding PeeringDB provides.

**Comment by gmazoyer** [comment]
Now that the PeeringDB code as been refactored, it's only a matter of displaying data.

**Comment by gmazoyer** [comment]
Fixed in [2ee2cea](https://github.com/peering-manager/peering-manager/commit/2ee2ceae22d0a98e9f7020b24a33d912a7b00206)
