### ISSUE TITLE
PeeringDB sync issue with duplicated IXP records

### ISSUE THREAD

**Issue by rlanyi** [peering-manager/peering-manager#323]
### Environment
* Python version:  3.9.0
* Peering Manager version: v1.2.1

### Steps to Reproduce

There are no steps to reproduce, this happened when the PeeringDB sync task was run from cron.

### Expected Behavior

For all ASNs I'd expect that no IXP peering sessions are duplicated on the Available Sessions tab. Every IXP IP (IPv6 and IPv4) should only appear once.

### Observed Behavior

For a specific ASN, AS57164 all rows in the Available Sessions tab were duplicated, every IXP session has two rows with the same data, the only difference is that one of them contains the AS-SET and the other one doesn't.

It is important that this happened with a newly created ASN record in PeeringDB and my assumption is that at the initial sync the AS-SET field was still unset. At a second sync it was filled already and maybe Peering Manager didn't find the existing ones in the database.

![image](https://user-images.githubusercontent.com/13754361/99158250-34282a80-26d1-11eb-9e5d-4f09b570f92a.png)

**Comment by respawner** [comment]
Closed by a2c3de4.
