### ISSUE TITLE
Suggestion - Change from bgpq3 to bgpq4 on next releases

### ISSUE THREAD

**Issue by fischerdouglas** [peering-manager/peering-manager#325]
### Environment
Same as the latest version of peering-manager/docker

### Proposed Functionality
Replace bgpq3 by bgpq4.
P.S.1: In my free time I'm studying to build alias packages(update-alternatives) between bgpq3 and bgpq4.

### Use Case
bgpq4 was forked from bgpq3 almost a year ago.
The contributors are very active since then. and received a few new features and several improvements.

bgpq4 has some improvements on performance compared to bgpq3, and also includes some extra formats outputs like mikrotik. And also some improvements on json format(used by bird and openbgpd).
P.S.: Also on my free time I'm working to include the huawei XPL format.

### External Dependencies
Bgpq4 has its sources public on https://github.com/bgp/bgpq4.
Has also an automated task to build distro packages that were accepted 

Most of the recent version of distros has already accepted it in the official repository.
https://pkgs.org/search/?q=bgpq4

**Comment by respawner** [comment]
The `BGPQ3*` settings can be changed to use `bgpq4` instead. These settings are just used to know where the binary is and what parameters to give to it. For instance, you could change the `BGPQ3_PATH` setting to point to the `bgp4` binary, other settings may need to be modified as well.

I did not take a look at `bgpq4` yet so I assume it is mostly compatible with `bgpq3`. Feel free to correct me if I'm wrong though and we will find a way to make `bgp3` and `bgp4` usable.

**Comment by jamesditrapani** [comment]
BGPQ3 and BGPQ4 are pretty much identical from a UX point of view. The params that are used in the Peering Manager use case are all the same in BGPQ4. Currently, changing the binary location to BGPQ4 works exactly as expected.

**Comment by respawner** [comment]
Path to BGPQ`x` can be changed in config as well as parameters. Symlink should also work for lazy people :)
