### ISSUE TITLE
External user authentication

### ISSUE THREAD

**Issue by dunc623b** [peering-manager/peering-manager#330]
### Proposed Functionality
Ability to use external authentication via the proxy (e.g. Nginx) by setting the appropriate headers (e.g. HTTP_REMOTE_USER)

New users successfully authenticated would get created and dropped into default group.

Similar was discussed for Netbox [here](https://github.com/netbox-community/netbox/issues/2328) and subsequently implemented [here](https://github.com/netbox-community/netbox/pull/4299)

### Use Case
Allows authentication to be handled at the proxy stage.

**Comment by gmazoyer** [comment]
As mentioned we should implement some kind if auth backend like NetBox does. If we try to follow the same kind of implementation, users could even use the same code that they use for NetBox.

We should keep in mind to rewrite the current auth backends we support by keeping in the code (LDAP and RADIUS). However we should get rid of the dependencies they need in the `requirements*.txt` and instead document them. We also need to add support to the upgrade script to use a local requirements file so user can import needed dependencies for their auth backends.

**Comment by davidc** [comment]
Integrating python-social-auth would be nice, but even just accepting the HTTP_REMOTE_USER and auto-creating users in an admin-defined group would be sufficient to get going, then the webserver can handle the auth and peering manager can trust it - this is how Netbox started.
