### ISSUE TITLE
Enable Peering Manager - Authentication via OIDC (SSO)

### ISSUE THREAD

**Issue by rgarcia89** [peering-manager/peering-manager#336]
### Environment
* Python version: container (python:alpine3.12)
* Peering Manager version: 1.2.1

### Proposed Functionality
Next to LDAP and Radius it would be nice if it would be possible to authenticate via OIDC for SSO again Peering Manager. I am rolling this out currently in my company using keycloak, which makes life so much better. One click and you are logged in.

### External Dependencies
Some Python package will be surely needed

**Comment by respawner** [comment]
It most likely fit into #330.

To be honest, having to manage several authentication backends will probably end up in a lot of work. It probably worth the shot to provide a generic authentication framework on top of which users can have the ones they'd like.

**Comment by rgarcia89** [comment]
That's surely correct. However I was thinking that OIDC would be probably easy to implement as I have seen already a few plugins that are available for django. Also it is a pretty popular getting standard for authentication. 

I think the question would be more, what authentication protocols are popular or becoming the new standard. As I don't think that it will be possible to fit into everybody needs.

**Comment by gmazoyer** [comment]
Tracking in #330
