### ISSUE TITLE
Unable to import from PeeringDB

### ISSUE THREAD

**Issue by mattjepp** [peering-manager/peering-manager#345]
### Environment

Python version: 3.7.3
Peering Manager version: 1.3.1-dev (as of 17:15UTC)

### Steps to Reproduce

When attempting to import an IX with PeeringDB using the link at the top of the Internet Exchanges page, I receive the following error message:

```
Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

              <class 'AttributeError'>
              

              'NoneType' object has no attribute 'ip'
              

              Python version: 3.7.3
              Peering Manager version: v1.3.1-dev
```

There's nothing logged in the logs/peering-manager.log file relating to this error.

I've previously upgraded from a 1.2 dev release to the 1.3 dev release, I don't know if perhaps something didn't get upgraded correctly? I had to manually add my local ASN and set the Affiliated flag.

PeeringDB syncing seems to be working correctly.

**Comment by respawner** [comment]
Did you try to do a full sync of PeeringDB data using the following commands?

```
$ python3 manage.py peeringdb_sync --flush # cleanup
$ python3 manage.py peeringdb_sync  # full sync
```
