### ISSUE TITLE
Support custom NAPALM drivers (e.g. Huawei VRP)

### ISSUE THREAD

**Issue by coredidan** [peering-manager/peering-manager#347]
Hi, we run eBGP on few Huawei VRP devices and it's would be great if PM would support it.

There is already  installed [napalm-huawei-vrp](https://github.com/napalm-automation-community/napalm-huawei-vrp.git) library, but with zero effect :(

**Comment by respawner** [comment]
The current supported platforms is a hard-coded list which corresponds to NAPALM base supported drivers. To support community drivers, platforms list must be changeable by users with a field to give the name of the NAPALM driver to user for each platform.

**Comment by coredidan** [comment]
You are right, in the same Netbox this is exactly what was done - when you manually add Device Platform, you manually enter name of the napalm driver and when accessing a device, napalm load a library with that name

**Comment by routerfixer** [comment]
We use Nokia SROS for some peering edge, I would like to see the ability to add Napalm drivers too, so far I hacked together an ansible playbook to pull the config from peering-manager and deploy. I'm only using this in a lab today, needs lots more testing before I will trust it with production.
