### ISSUE TITLE
Potential peering sessions not visible

### ISSUE THREAD

**Issue by dnowacki91** [peering-manager/peering-manager#350]
Upon update to the most recent Docker image release, the Potential Peering Sessions have stopped working.

My understanding is that the current expected behaviour contrary to the documentation, as per, #305 is that "check_for_ix_peering_sessions" should no longer be executed (this option indeed doesn't exist any more) and that check shall execute automatically when a new ASN is added and then periodically in the background.

Unfortunately this is not the case; Upon adding a new ASN despite sharing multiple common IXs there's no potential session to create. This doesn't seem to update in the background either (over 30 minutes), there doesn't appear to be any manual way of invoking this either.

Can you please advise?

**Comment by respawner** [comment]
This sounds like an issue from the Docker setup. As of `1.3.0` a local copy of PeeringDB data is required for features using them. IIRC the Docker image will not setup cron jobs to update these data.

Note that the `potential_internet_exchange_peering_sessions` field is not used anymore and potential sessions are retrieved when required (no cron job needed).

Can you confirm that you do/don't have PeeringDB data synced locally with the help of the `peeringdb_sync` command?

**Comment by dnowacki91** [comment]
Thank you.

I do have a copy of the PeeringDB data; I went to the AS again after downloading them the potential exchanges weren't there, I then removed and re-added the AS and that didn't resolve it either.

<img width="726" alt="Screenshot 2021-01-24 at 15 51 29" src="https://user-images.githubusercontent.com/55637685/105635703-3f7b9d00-5e5c-11eb-9a47-2ea10be8437a.png">

**Comment by respawner** [comment]
Good. Then it seems that there are issues linking IXPs objects with PeeringDB's. Could you take a look at the administrator view and look for each IX if it as an `IXLan` linked to it?

**Comment by dnowacki91** [comment]
It appears that following the upgrade the existing Internet Exchanges are missing certain parameters.

<img width="586" alt="Screenshot 2021-01-27 at 21 30 30" src="https://user-images.githubusercontent.com/55637685/106056740-ea9f8700-60e6-11eb-973f-436dca6320f4.png">

This should be not too hard to backfill. Could you help with a suggestion how to identify correct Peeringdb netixlan for Peeringdb IX?

**Comment by respawner** [comment]
Do you have a local AS set on your IX objects. If not you should set it to the one that you use as affiliated AS. Once this done, Peering Manager should be able to fill to PeeringDB's `NetIXLan` and `IX` fields by itself when you'll reach the IX overview page.

**Comment by jamesditrapani** [comment]
@dnowacki91 Looping around on this, how did you go?

**Comment by gmazoyer** [comment]
This should be fixed with the latest releases as PM now fills PeeringDB fields automatically, as long as a local AS is selected.
