### ISSUE TITLE
No preferred affiliated autonomous system selected.

### ISSUE THREAD

**Issue by jasonbothe** [peering-manager/peering-manager#359]
### Proposed Changes
Hello. I'm not sure how to clear the error of "No preferred affiliated autonomous system selected." Also, is there a way to import the IPv4/v6 addresses from PeeringDB. Seems painful to have to manually enter these things.  Thanks.

**Comment by respawner** [comment]
You need to create an autonomous system and select the affiliated checkbox. Then you'll be able to select the AS from the dropdown next to your user menu. PeeringDB records can be used for importing but you'll have to sync the Peering Manager instance with PeeringDB, [see this part of the doc](https://peering-manager.readthedocs.io/en/latest/setup/7-scheduled-tasks/#caching-in-the-local-database).

If you have other questions, please use [Discussions](https://github.com/peering-manager/peering-manager/discussions) or Slack.
