### ISSUE TITLE
Database migration problem from 1.2.1 to 1.3.1

### ISSUE THREAD

**Issue by Guigui37** [peering-manager/peering-manager#360]
### Environment
* Python version:  3.8.5
* Peering Manager version:  1.2.1 to 1.3.1

### Steps to Reproduce
Upgrading peering manager from 1.2.1 to 1.3.1 using official ansible playbook, and also while running upgrade.sh script.

### Expected Behavior
Upgrading goes to the end

### Observed Behavior
psycopg2.errors.ObjectInUse: cannot ALTER TABLE "peering_directpeeringsession" because it has pending trigger events

Should the script takes care of all migration steps or should I migrate to 1.3.0 first then 1.3.1 ?

Thanks

**Comment by Guigui37** [comment]
Just tried upgrading following path 1.2.1 -> 1.3.0 -> 1.3.1 -> 1.3.2 without any problem.

**Comment by respawner** [comment]
No need to go through every releases, however I highly recommend to go to 1.3.2 directly as it will avoid migration failures that can happen with 1.3.0 or 1.3.1. Release of the 1.3.x train before 1.3.2 try to perform DB operations into the same transaction for operations that can't be in the same transaction.
