### ISSUE TITLE
Allow Config Deployment to Git

### ISSUE THREAD

**Issue by jamesditrapani** [peering-manager/peering-manager#365]
### Environment
* Python version:  3.7.3
* Peering Manager version:  Main

### Proposed Functionality
Allow configuration deployment to be commited to a git repo instead of deployed directly to a device. 

### Use Case
Allowing Peering Manager to be hooked directly into an existing Network CI/CD deployment. Ideally, I'd say that you can either enable direct config push OR you commit your configuration diffs to a git repo. Probably don't want to run a mix of both as this may cause issues with state of device config versus git repo.

**Comment by ggiesen** [comment]
I'd expand this to say allow for an arbitrary script can be run so it's more flexible. So you can script it to deploy to git, or to use an existing automation framework, or whatever you want to do with the config.

**Comment by forkwhilefork** [comment]
I would really like to see this. I don't want to do any config pushes without reviewing the diff first, so I want to construct a pipeline where peering manager generates the config based on the template, diffs it against the running config, then, if there are any changes, sends a webhook to slack. Ideally I'd be able to "approve" it by clicking a button on the slack message also.

I can construct all of the slack stuff, but being able to take that config and do something arbitrary with it would be a big help toward this functionality.
