### ISSUE TITLE
BGP Event Log

### ISSUE THREAD

**Issue by jaakub** [peering-manager/peering-manager#368]
### Environment
* Python version:  3.8.5
* Peering Manager version:  1.3.3-dev

### Proposed Functionality

Create an event view on the home page, or perhaps add another menu option, in which you can see recent BGP down events.  An event would be added when the session state changes from Established to anything else.  This would obviously rely on fairly frequent session polling.
 

### Use Case

This would be useful for NOC to see the history of recent events.  This does not aim to replace existing monitoring or syslog platforms but adds additional state history to peering-manager.

**Comment by gmazoyer** [comment]
This issue is probably (in some ways) linked with #53. I wouldn't put all event logs in Peering Manager, that seems out of scope. However I could imagine a connector to another tool to display these events.

**Comment by jamesditrapani** [comment]
I tend to agree with @gmazoyer here. Your feature proposal is something that more than likely should be handled by a monitoring platform/general diagnostic tooling rather than a Peering source of truth/management/deployment platform. Nonetheless, the idea can be thrown into the backlog :)
