### ISSUE TITLE
Peeringdb import not available

### ISSUE THREAD

**Issue by richardhkirkando** [peering-manager/peering-manager#373]
Hi,

Fresh install on ubuntu 20.04, python 3.8.5, peering-manager v1.3.3-dev (pulled March 19).

I have run the manage.py peeringdb_sync script, and the main page shows a successful synchronization.  I've also created my own ASN and set it as affiliated.  When I go to the Internet Exchanges page, I only have an option to manually add.  From what I gather, there should also be an import option here.

Is there a prerequisite I may have missed before the import option is available?

**Comment by gmazoyer** [comment]
The button does not appear with the main branch code. This is a regression that needs to be fixed for next release.
