### ISSUE TITLE
After "Import from Router" peering sessions list needs to be manually refreshed

### ISSUE THREAD

**Issue by wtremmel** [peering-manager/peering-manager#385]
### Environment
* Python version:  Version from Docker container
* Peering Manager version:  Docker container

### Steps to Reproduce
- Go to "Internet Exchanges"
- add an Internet Exchange 
- click on "Import from Router
- Sub-window shows "4 sessions imported"

### Expected Behavior
- list of imported session is shown in Internet Exchange Peering Sessions

### Observed Behavior
- list is still empty, reload of page is necessary
- auto-refresh would be nice

**Comment by gmazoyer** [comment]
Importing sessions was moved to a asynchronous job as of 46178ba830205ce1e8b80b0a6db79ddf3a4ee4b6. It means that we will no longer block user while the import process is ongoing, therefore we can no longer know if the current window needs to be refreshed.
