### ISSUE TITLE
Upgrading to 1.3.x leaves local_autonomous_system unset

### ISSUE THREAD

**Issue by mngan** [peering-manager/peering-manager#410]
### Environment
* Python version:  3.8.5 
* Peering Manager version: v1.3.3 

### Steps to Reproduce
Take a pre v1.3.x database and run `./manage.py migrate`. This will complete successfully, but none of the IX, DPS or Router objects will have the local_autonomous_system set. 

### Expected Behavior
It is unclear what should happen here if you want to support multiple ASN's. But prior to v1.3 people would have only a single `MY_ASN` configured. It would make sense to default all the local_autonomous_system values to that ASN unless it was explicitly set otherwise (e.g in DPS). 

### Observed Behavior

Having these objects without local_autonomous_system set causes UI issues, but can be fixed by setting the value. In some ways, this is could be addressed as a documentation issue by alerting the user when they perform the migration that additional steps are required to fill in the data. 

Having local_autonomous_system set to NULL, will cause problems with future migrations (e.g `peering/migrations/0075_backfill_service_ref.py`) until the problem is addressed.

**Comment by jamesditrapani** [comment]
Potentially fixed by 476e3dfd3ac542905f0324a8a233bb30be54500e

**Comment by gmazoyer** [comment]
Fix committed in 476e3df.
