### ISSUE TITLE
E-Mail preview does not render subject correctly.

### ISSUE THREAD

**Issue by Paktosan** [peering-manager/peering-manager#418]
### Environment
* Python version: 3.6.8
* Peering Manager version: 1.3.2

### Steps to Reproduce
1. Create a email template using a variable in the subject
2. Try to preview the template

### Expected Behavior
The modals title should show the rendered subject

### Observed Behavior
The modals title shows the subject but without the variable

**Comment by gmazoyer** [comment]
The preview feature (for both emails and templates) will be removed in next released due to its "hackish" coding. We will re-introduce the feature once we come up with a better solution
