### ISSUE TITLE
Add VyOS as router platform

### ISSUE THREAD

**Issue by Paktosan** [peering-manager/peering-manager#422]
### Proposed Functionality
Add support to use VyOS as a router platform.

### Use Case
When using a router running VyOS.

### External Dependencies
A [Napalm Library](https://github.com/napalm-automation-community/napalm-vyos) already exists for it.

**Comment by gmazoyer** [comment]
In 1.4.0 platforms will not longer be a hard coded list. Users will be able to create new platforms and use community NAPALM driver with them (as long as the Python package is installed).
