### ISSUE TITLE
E-mail template error 'my_as' is undefined

### ISSUE THREAD

**Issue by freedomwarrior** [peering-manager/peering-manager#434]
### Environment

* Python version:  3.8.5
* Peering Manager version:  1.3.3-dev 13b23f1

### Steps to Reproduce
Create e-mail template with jinja2 template from Docs -> Templating -> Peering Request E-mail
Than try to send e-mail from template.

### Expected Behavior
Auto generated message from template

### Observed Behavior
It generate message with one string: `'my_as' is undefined`
![image](https://user-images.githubusercontent.com/6192135/119393958-5206c580-bcda-11eb-89a8-0a4363b1f9da.png)

**Comment by gmazoyer** [comment]
If don't use a stable release, you should referer to the doc which is built for non stable code.

https://peering-manager.readthedocs.io/en/latest/templating/examples/peering-request-email/
