### ISSUE TITLE
Memory Leak on AS list

### ISSUE THREAD

**Issue by Paktosan** [peering-manager/peering-manager#446]
### Environment

* Python version: 3.6.8
* Peering Manager version: 1.4.1

### Expected Behaviour
Show the list of AS without massive memory usage

### Observed Behaviour
Got the list of AS with massive memory usage

As a first measure, I used `memory_profiler` to generate this report. So far I have not gathered additional intel.

![peering-manager](https://user-images.githubusercontent.com/4009269/121873912-27bb8d00-cd07-11eb-82f1-ca8554514736.png)

**Comment by jamesditrapani** [comment]
Are you loading `/autonomous-systems/`?

**Comment by gmazoyer** [comment]
Do you use the prefix caching code?

**Comment by Paktosan** [comment]
Yes, I mean `/autonomous-systems/`.
You mean IRR AS-SET Prefixes? I have a systemd task running `manage.py grab_prefixes` periodically.

**Comment by gmazoyer** [comment]
This is a suspect to me. Fetched prefixes are stored in a field which is loaded when loading the AS list view. It is not needed though. Changing the queryset of this view to `AutonomousSystem.objects.defer("prefixes")` could help. If it does make things better, we'll have to fix this in several places.

**Comment by Paktosan** [comment]
Limiting the view will probably help. But I think we have to look deeper.
I tried to view our entry for AS6939 at `api/peering/autonomous-systems/19/` but the request pins the gunicorn process to 100%CPU on one core and times out with HTTP504 after a while...

**Comment by gmazoyer** [comment]
The problem is the same. It preloads lots of data. After all you are preloading HE.net prefixes...

**Comment by gmazoyer** [comment]
Can you test commit 2d1ae1a to see if it improves memory load?

**Comment by Paktosan** [comment]
Yes, with this commit, memory usage looks fine again. The mentioned API call is of course still not working, but this should be fixed as soon as I have hardware on hand that is not 13 years old.
