### ISSUE TITLE
Upgrading from 1.3.2 to 1.4.2 issues

### ISSUE THREAD

**Issue by routerfixer** [peering-manager/peering-manager#447]
First of all great work, Peering-Manager has helped us to automate our peering and reduce config errors to zero. 

A few points on the 1.4.2 release.
In Internet exchanges view none on the IXPs show session count
<img width="452" alt="Screenshot 2021-06-16 at 09 46 05" src="https://user-images.githubusercontent.com/16070047/122188277-b6efae80-ce87-11eb-859b-117eef852ed6.png">

The sessions do show inside a specific IXP
<img width="453" alt="Screenshot 2021-06-16 at 09 50 56" src="https://user-images.githubusercontent.com/16070047/122188938-6036a480-ce88-11eb-87cf-fccae3e05371.png">

Config generated from template also does not include any sessions
<img width="457" alt="Screenshot 2021-06-16 at 09 53 49" src="https://user-images.githubusercontent.com/16070047/122189383-cae7e000-ce88-11eb-8759-120373c424b6.png">
all worked correctly on version 1.3.2

Also can we get the Raw config option back? We used this to fetch the config for routers that napalm will not work with and then use ansible to deploy.

**Comment by gmazoyer** [comment]
From `1.3`  to `1.4` templating as been revamped leveraging custom Jinja2 filters. You can find new filters and exposed variables in the [documentation](https://peering-manager.readthedocs.io/en/stable/templating/). There are also some examples available there.

As for the raw config option, it has been removed for now as the config is generated asynchronously. We could however bring it back, within a specific path that will create the config in a synchronous way (which is suitable for "small" configs, but not "big" ones)

**Comment by routerfixer** [comment]
I did try using the new example templates in the docs IOS-XR one specifically but that to just produced a 1 line config

router bgp 65105
 
I will try a fresh install on a new VM later to see if that makes any difference.

I will stay on 1.3.2 for production as this is working well, we cant use Napalm to deploy to our Nokia SRos routers as the Napalm driver needs a newer version than we are using today, Change management and customer SLAs mean that wont be changing anytime soon.

**Comment by gmazoyer** [comment]
The example had a bad reference to a var. I fixed it in df11e1a. A fresh install won't fix it then. Have a try with the template from the [dev branch doc](https://peering-manager.readthedocs.io/en/latest/templating/examples/cisco-iosxr/).

**Comment by routerfixer** [comment]
The dev branch template fixed the config, it needs the last } on the end of line 3 removing.
