### ISSUE TITLE
Support for ZTE Core Router ZXR10 M6000-S

### ISSUE THREAD

**Issue by jeanfrancis** [peering-manager/peering-manager#460]
Hi,

I woul like to make a feature request for the support of ZTE Core Router ZXR10 M6000-S

**Comment by jamesditrapani** [comment]
Peering Manager uses NAPALM drivers for its network interaction pieces. You can see the list of support NAPALM drivers here https://napalm.readthedocs.io/en/latest/support/

If ZTE is not there then you may need to log a feature request on the NAPALM GitHub.
