### ISSUE TITLE
BFD Fields

### ISSUE THREAD

**Issue by jaakub** [peering-manager/peering-manager#464]
**Environment**

Python version: 3.8.5
Peering Manager version: 1.3.3-dev

**Proposed Functionality**

Add bfd minimum interval and bfd multiplier fields to BGP session / BGP group objects.

**Use Case**

Some direct PNI solutions require a custom bfd setup and being able to override this per peer or per BGP group would be great.  At the moment, the only method of adding bfd is hardcoded within the template (I think).

**External Dependencies**

N/A

**Comment by jamesditrapani** [comment]
@jaakub Will discuss this with @gmazoyer. If anything I'd say this would only be for Direct Sessions

**Comment by jamesditrapani** [comment]
@jaakub After a discussion with @gmazoyer, we've decided that to avoid blotage of fields in the Session parameters, we feel like this is better suited to a use of `Tags`. As such, we're not going to go ahead with implementing these fields explicitly.

If you need a hand with how to configure tags & use them in templating, let me know and I can throw something together for you!
