### ISSUE TITLE
Configure/Poll Routers as Jobs from Management Scripts

### ISSUE THREAD

**Issue by mngan** [peering-manager/peering-manager#470]
### Environment

* Python version:  3.8
* Peering Manager version:  1.3.2

### Proposed Functionality

The UI can now submit router configuration jobs. It would be nice if the management script could also do the same so you could potentially get some parallelism (one job per router) via the worker. The same could also apply to polling the BGP sessions of the routers. Right now, this is all done on the main thread, but it could be sent through as a set of jobs for a worker pool to process. This will cut down on the duration to run these periodic jobs with a large number of routers/BGP groups. 

### Use Case

Large numbers of routers and BGP groups will cause `poll_peering_sessions` and `configure_routers` to take an extremely long time to run. Using jobs to get better parallelism would help a lot here. The more rq workers you spawn the more parallelism you get. So, in the default case with 1 worker, it will be about the same duration. 

### External Dependencies

None

**Comment by gmazoyer** [comment]
Linked to #334

**Comment by mngan** [comment]
Oh :) I should really check my own issues.

**Comment by gmazoyer** [comment]
There are no real blockers to implement this. Maybe we should add a flag for the script to start jobs or to run the process in a synchronous mode like it currently does. Maybe something like:

```
python manage.py poll_bgp_sessions --tasks
```
or
```
python manage.py poll_bgp_sessions --no-tasks
```

What's your opinion?
