### ISSUE TITLE
Add a `communities` Jinja filter for groups and sessions

### ISSUE THREAD

**Issue by mirackle-spb** [peering-manager/peering-manager#489]
Interface have separate community list for each peering session.
But when i try to access it - "'peering.models.models.InternetExchangePeeringSession object' has no attribute 'communities'" error.
Reproduced always.
Template code
`{{- session.communities.all() | filter(type="ingress") | iterate('slug') | join(' ') -}}{{ " " }}`
same with internet_exchange - is working well.

Vesion - lastes git - 1.4.5-dev

**Comment by gmazoyer** [comment]
We can add a new jinja filter to fetch communities (a bit like routing policies) like `{{ session | communities }}`, if it can help in template simplification.
