### ISSUE TITLE
Cimmunity filters not working as desined

### ISSUE THREAD

**Issue by mirackle-spb** [peering-manager/peering-manager#491]
### Environment

* Python version:  3.8
* Peering Manager version:  1.4.6-dev

{%- if internet_exchange.communities -%}{{ internet_exchange | communities | filter(type="ingress") | iterate('slug') | join(' ') }}{{ " " }}{% endif -%}
and
{%- if session | communities -%}{{ session | communities | filter(type="ingress") | iterate('slug') | join(' ') }}{{ " " }}{% endif -%}

Gives me a error "cannot filter data not in the database", but must output filtered by direction communities for ixp or session.

**Comment by gmazoyer** [comment]
Fixed in 20e1fe5

**Comment by mirackle-spb** [comment]
`{%- if session | merge_communities -%}{{ session | merge_communities | filter(type="ingress") | iterate('slug') | join(' ') }}{{ " " }}{% endif -%}` now gives me a error 'cannot filter data not in the database'
