### ISSUE TITLE
API not working with Peering Manager in a directory (with nginx)

### ISSUE THREAD

**Issue by tweippert** [peering-manager/peering-manager#499]
### Environment

* Python version:  3.9.2
* Peering Manager version:  (HEAD detached at v1.4.5)

Accessing Peering Manager within a directory:

```
    location /peering/static {
        alias /opt/peering-manager/static;
    }

    location /peering {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwared-Proto $scheme;
        proxy_pass http://127.0.0.1:8010;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

```
BASE_PATH  set in configuration.py 

```
# Base URL path if accessing Peering Manager within a directory.
BASE_PATH = "peering/"

```
### Steps to Reproduce

Accessing the API of Peering Manager:

`http://mgmt04.weiti.home/peering/api/users/`

### Expected Behavior

Getting the API Pages

### Observed Behavior

Getting 404 - not found

Log of NGinx:

`2021/10/16 10:52:06 [error] 55884#55884: *34450 "/usr/share/nginx/html/peering/api/users/index.html" is not found (2: No such file or directory), client: 172.18.49.160, server: mgmt04.weiti.home, request: "GET /peering/api/users/ HTTP/1.1", host: "mgmt04.weiti.home"`

**Comment by tweippert** [comment]
It seem's that my installation also not working if i try to use the root for Peering Manager. Not related to subdirectory usage it seems. Any idea's what to check?

**Comment by gmazoyer** [comment]
Can you point out the part of the documentation that needs to be fixed so we can improve it?

**Comment by tweippert** [comment]
Added an PR to show my changes in the nginx configuration
