### ISSUE TITLE
Server Error when removing max prefix from an AS

### ISSUE THREAD

**Issue by wtremmel** [peering-manager/peering-manager#504]
### Environment

* Python version:  3.9.2
* Peering Manager version:  1.4.6

### Steps to Reproduce

* remove ipv4 and ipv6 max prefix from an AS
* unselect max-prefix-sync for v4 and v6 from PeeringDB
* click on save

### Expected Behavior

* all good

### Observed Behavior

Error message (for whatever reason in German)
```
<class 'django.db.utils.IntegrityError'>
              
              FEHLER:  NULL-Wert in Spalte »ipv6_max_prefixes« verletzt Not-Null-Constraint
DETAIL:  Fehlgeschlagene Zeile enthält (7, 51531, DE-CIX Services, , null, null, 2021-11-05 08:56:12.111095+00, RIPE::AS-DECIX-SERVICES, f, f, t, 2021-05-07 14:48:58.937828+00, , , , {"ipv4": [{"exact": true, "prefix": "5.1.66.0/24"}, {"exact": tr..., t, f).
```

Translation: Null-value in Column ipv6-max-prefixes violates not-null-constraint

**Comment by Paktosan** [comment]
Full stack trace can be found here: https://gist.github.com/Paktosan/a8046aae686732874b721775ea8c6b8e

**Comment by Paktosan** [comment]
I can see why this is not allowed.
Good practices would say that you always want maximum prefixes.
But I think we can allow null values here as long as templates account for it.
And even if we don't allow it, we should show a better error message for it or highlight it as error even before sending the form.

**Comment by gmazoyer** [comment]
Default value for max prefix is `0` which is considered as null. Any reasons to use `NULL` over `0` in that case?

**Comment by Paktosan** [comment]
While I can't think of a scenario right now, you may want to accept no prefixes from a peer, so set max prefix to `0`.
This is different from not setting max prefix at all.
I would write my template in a way that if max prefix is set to `NULL` I don't execute the command on the router at all.
But if I set max prefix to `0` then I would execute the command with a value of `0`.

**Comment by gmazoyer** [comment]
> While I can't think of a scenario right now, you may want to accept no prefixes from a peer, so set max prefix to `0`. This is different from not setting max prefix at all. I would write my template in a way that if max prefix is set to `NULL` I don't execute the command on the router at all. But if I set max prefix to `0` then I would execute the command with a value of `0`.

It is a bit strange for me to reject all prefixes of a peer by setting a prefix limit to 0 but why not (I'd use a policy instead). Note that if we allow `NULL` values in the database for prefix limit using `{% if autonomous_system.ipv6_max_prefixes %}` won't work like now as it will match prefix limit being `NULL` and `0`.

**Comment by wtremmel** [comment]
setting max-prefix to 0 does not reject all prefixes but tears down the BGP session if one prefix is being announced - no idea what the use-case for this is but there might be one...

And IMHO setting it to 0 and setting "no max prefix" are two different things... I actually do not mind either or, a help text like "set to 0 to disable" and having that as a default value if the input field is empty would also be ok...

**Comment by jamesditrapani** [comment]
Usecase for `max_prefixes` being set to zero is when advertising to a route collector you may wish to set to `0` to ensure you do not accept anything from a peer that should **NEVER** be sending you anything. I think we do need a way to differentiate between **do not send me anything** and **I don't really care how many prefixes you send me**, although I am still an advocate for ensuring max-pref on all sessions

**Comment by gmazoyer** [comment]
Fair enough, lets allow `NULL` values for max prefix fields. 2 things not to forget, add a help text to each field, update the documentation to take into account the difference between `0` and `NULL`.

**Comment by jamesditrapani** [comment]
Allowing `NULL` will break templates, especially when trying to do `> 0` comparison. Is allowing `NULL` directly on this field the best way?

**Comment by gmazoyer** [comment]
I don't see a lot of options here:

1. allow `NULL` value (an option to add on the field), checks need to become `{% if a.ipv4_max_prefixes is not none and a.ipv4_max_prefixes > 0 %}`, we could provide custom utility filters too
2. allow a special value such as `-1`, need to convert the field from `PositiveIntegerField` to `IntegerField` (seems overkill for just a one specific value)
3. add extra fields (boolean and one per address family) to tell if max prefix fields must be used, templates will require changes too

**Comment by jamesditrapani** [comment]
> I don't see a lot of options here:
> 
> 1. allow `NULL` value (an option to add on the field), checks need to become `{% if a.ipv4_max_prefixes is not none and a.ipv4_max_prefixes > 0 %}`, we could provide custom utility filters too
> 2. allow a special value such as `-1`, need to convert the field from `PositiveIntegerField` to `IntegerField` (seems overkill for just a one specific value)
> 3. add extra fields (boolean and one per address family) to tell if max prefix fields must be used, templates will require changes too

Based on the above options, I think point one is going to be the best. What would you imagine the utility filter to do? E.g. check if value is not `NULL` or `0`?
