### ISSUE TITLE
Gunicorn missing in requirements.txt?

### ISSUE THREAD

**Issue by vidister** [peering-manager/peering-manager#513]
### Peering Manager version

1.4.5

### Python version

3.7

### Steps to Reproduce

I upgraded Peering-Manager switching to the newest git tag and running the `upgrade.sh`.

### Expected Behavior

Upgrade to succeed

### Observed Behavior

After that the peering-manager systemd unit wouldn't start since the gunicorn-binary was missing:
```
Nov 16 16:00:23 IHVS0281-PEERING-MANAGER systemd[1]: Started Peering Manager WSGI Service.
Nov 16 16:00:23 IHVS0281-PEERING-MANAGER systemd[1204]: peering-manager.service: Failed to execute command: No such file or directory
Nov 16 16:00:23 IHVS0281-PEERING-MANAGER systemd[1204]: peering-manager.service: Failed at step EXEC spawning /opt/peering-manager/venv/bin/gunicorn: No such file or directory
Nov 16 16:00:23 IHVS0281-PEERING-MANAGER systemd[1]: peering-manager.service: Main process exited, code=exited, status=203/EXEC
Nov 16 16:00:23 IHVS0281-PEERING-MANAGER systemd[1]: peering-manager.service: Failed with result 'exit-code'.
Nov 16 16:00:53 IHVS0281-PEERING-MANAGER systemd[1]: peering-manager.service: Service RestartSec=30s expired, scheduling restart.
Nov 16 16:00:53 IHVS0281-PEERING-MANAGER systemd[1]: peering-manager.service: Scheduled restart job, restart counter is at 6.
Nov 16 16:00:53 IHVS0281-PEERING-MANAGER systemd[1]: Stopped Peering Manager WSGI Service.
```

I added gunicorn to `requirements.txt`, rerun the upgrade.sh to rebuild the venv and then it worked.

Did I miss something out here or is it really missing?

**Comment by wtremmel** [comment]
See release notes:
"Note: as of this release, WSGI servers such as gunicorn or uwsgi are no longer listed as dependencies. You may continue to list them as local dependencies in your setup by creating a local_requirements.txt next to requirements.txt. This is also true for LDAP and RADIUS authentication packages."

**Comment by gmazoyer** [comment]
As @wtremmel mentioned, this is on purpose. See the [1.4.6 release notes](https://github.com/peering-manager/peering-manager/releases/tag/v1.4.6) for more details.

**Comment by vidister** [comment]
You are totally right, sorry.
