### ISSUE TITLE
peeringdb_sync error validating facility available_voltage_services

### ISSUE THREAD

**Issue by 2bithacker** [peering-manager/peering-manager#514]
### Peering Manager version

v1.4.5 (docker)

### Python version

3.10

### Steps to Reproduce

1. run `python3 manage.py peeringdb_sync`

### Expected Behavior

Command should complete without errors.

### Observed Behavior

I get errors around `available_voltage_services` which leads to problems with other objects that refer to the affected facilities. I've seen this with multiple facility ids, so it's not isolated to just this one example:

```
sync ERROR error validating id: 8231 for model: facility#012{'available_voltage_services': ['Value "[\'240 VAC\']" is not a valid choice.']}
```

**Comment by gmazoyer** [comment]
This has been fixed (AFAIK) in [this commit](https://github.com/peering-manager/peering-manager/commit/e65bc248137fcffc16bd8a01fae2e39e14135962#diff-0636e3dec32a581bd8628a27c09024c15fb9d21116b7f2edd810ecb72e0b161c) which is part of 1.4.6.

**Comment by 2bithacker** [comment]
Ah yeah, sorry, I missed that in the release notes. Closing this out, will test with 1.4.6.
