### ISSUE TITLE
Use Jobs for CLI tools

### ISSUE THREAD

**Issue by mngan** [peering-manager/peering-manager#525]
### Peering Manager version

v1.4.6

### Feature type

New functionality

### Proposed functionality

The CLI management tools currently poll IX/BGP Groups and deploy configs to routers sequentially. Moving the code to configure routers and poll where it can be reused from the API and the CLI might be a good idea. 

### Use case

Using Jobs would be better for large installations to use groups and make use of multiple workers to improve concurrency.

**Comment by gmazoyer** [comment]
Related to #470?

**Comment by gmazoyer** [comment]
Closing to track this in #470.
