### ISSUE TITLE
IX-API v2 support

### ISSUE THREAD

**Issue by Paktosan** [peering-manager/peering-manager#537]
### Peering Manager version

v1.5.2

### Feature type

Change to existing functionality

### Proposed functionality

Support for version 2 of IX-API.

### Use case

Having support for v1 of the API is great but version 2 with more features is already released so v1 may not be supported by all IXs.

**Comment by gmazoyer** [comment]
Do you have any test feedbacks, crash stack traces or any other things that could help in bringing v2 and even v3 support? I don't have access to a v2 instance so I can't do much but with the publicly available API doc and some feedbacks I should be able to make it work.

**Comment by gmazoyer** [comment]
The change from `customers` to `accounts` from v2 onwards, while keeping v1 compatibility, should be addressed in 1e71224.

That said, I think we may have to think about supported versions. Versions 2 and 3 look more "finished" compared to version 1. If we find out that version 1 is not used by a majority of players maybe we should focus our efforts on versions 2 and 3 (dropping version 1).

**Comment by gmazoyer** [comment]
> Where are you finding v3? I can't see it on the website or GitLab.

There is nothing on the website or GitLab about v3 indeed. I just remember several talk of DE-CIX (Marcos) talking about v3 and what will be included in it (such as telemetry IIRC).

**Comment by tking** [comment]
>
Please reach out to LINX and AMS-IX directly. They can provide you with details.

**Comment by tking** [comment]
> 

Please reach out to LINX and AMS-IX directly. They can provide you with details.
