### ISSUE TITLE
Ability to mass sync AS entries with PeeringDB data

### ISSUE THREAD

**Issue by ggidofalvy-tc** [peering-manager/peering-manager#544]
### Peering Manager version

v1.4.6

### Feature type

New functionality

### Proposed functionality

The addition of a button, either on the Autonomous Systems or Cache Management page, which can be pressed to bulk sync all autonomous systems' set properties (IRR AS-SET, IPv4 Max Prefixes, IPv6 Max Prefixes) to the value in the PeeringDB Sync Cache. A command can also be exposed through manage.py in order to allow this to become a scheduled task (e.g. sync every AS just before a scheduled network configuration refresh).

I'd prioritise the command as it is the low-hanging fruit and has the most utility.

Optionally, sync only the selected autonomous systems (if this bulk sync can be done through the Autonomous Systems listing page).

### Use case

It can be quite exhausting to click through every single AS in Peering-Manager just to click on PeeringDB sync, having a bulk update button/command available would certainly cut down on the work needed to keeping the AS entries up-to-date.

In my opinion, it is better to proactively keep the AS entries updated rather than update only if it is necessary (i.e. when the IRR AS-SET changes or the IPv4/6 Max Prefix limit is hit).

As far as I can tell, there's no built-in way in Peering-Manager to do a bulk/mass sync of AS entries at the moment.

**Comment by gmazoyer** [comment]
This is what the `python manage.py peeringdb_sync` command is supposed to do in addition to caching the PeeringDB data locally. In v1.5.2, if you run that command manually with a verbosity of 2 (`-v2` flag), you should be able to see in the terminal the AS being updated.

**Comment by ggidofalvy-tc** [comment]
Okay, thanks for the clarification! The documentation wasn't quite clear about this, and I thought that command was analogous to the 'PeeringDB cache refresh' button in the Web interface.
