### ISSUE TITLE
IXP PI and Identity

### ISSUE THREAD

**Issue by ekrichbaum** [peering-manager/peering-manager#550]
### Change Type

Addition

### Area

User manual

### Proposed Changes

Attempted to add IX-API with DE-CIX.  Screen shows Identity and requests to choose one from the list. However, I'm unable to find this anywhere in the system to add an Identity.

https://peering-manager.readthedocs.io/en/latest/models/extras/ixapi/

**Comment by wtremmel** [comment]
The identity is pulled from DE-CIX once the IX-API connection is established. What did you enter in URL?

**Comment by ekrichbaum** [comment]
I can’t create the object in Peering Manager at all with something there.

 

https://api.de-cix.net

 

The screen asks for:



There isn’t anything in the drop down to populate so I assume it doesn’t try to contact the URL yet.

 

Eric

**Comment by wtremmel** [comment]
Correct URL is https://api.de-cix.net/api/v1/
You also need an v1 API key (the portal gives you an v2 API key, but IX-APIv2 is not yet supported by Peering Manager)

You can get your v1 API key by email from  api@de-cix.net (state that you need a v1 API key)

I also explain the whole process here in a video: https://de-cix.net/en/resources/videos-and-webinars/peering-manager-ix-api-integration

**Comment by gmazoyer** [comment]
A fix for IX-API version 2 is coming in next version. I added a note about supported versions in the documentation (see 7d0468e).
