### ISSUE TITLE
default-originate on BGP peers or groups

### ISSUE THREAD

**Issue by maznu** [peering-manager/peering-manager#566]
### Peering Manager version

v1.6.0

### Feature type

New functionality

### Proposed functionality

Add a "default originate" boolean to BGP peers (direct or IX) and BGP groups.

For discussion: if I have `True` in the BGP group, and a peering session which is in that group has `False`, what does that mean?  Or should the field on the peering session model have a tri-state field?  The values would then be interpreted as:

* `True` and `False` — indicating intended value of default originate for that peering, regardless of what it says in the associated BGP group
* and `None` — indicating "do whatever the BGP group has in its value for default originate"

### Use case

Peering Manager aims to be for all eBGP sessions, including downstream customers. Well, some customers might want default!

### Database changes

A boolean field to be added to the affected models.

**Comment by gmazoyer** [comment]
Advertising a default route is not always accomplished with a "default originate" kind of field/config stanza.

I use Juniper devices for years, to send a default route to a customer I use an export policy. This is probably the same kind of config for other vendors (Nokia, …). Actually, in my own instance of Peering Manager, I have a "Default Route" export routing policy.

If you really need a "default originate" information on an object, I'd suggest using a tag.

**Comment by maznu** [comment]
Actually, that you're using routing policy for this makes a lot of sense, and that I was guilty of "vendorthink".

However, your suggestion a tag reminded me that tags exist… and maybe they are the right place for other per-BGP-session configuration parameters (timers, etc).  I discuss this further in #505.

**Comment by gmazoyer** [comment]
Closing as discussion will continue in config context related issues.
