### ISSUE TITLE
Authentication using OAuth 

### ISSUE THREAD

**Issue by vilhelmprytz** [peering-manager/peering-manager#587]
### Peering Manager version

v1.6.2

### Feature type

New functionality

### Proposed functionality

It would be great if peering-manager could support authentication using OAuth (OpenID?) alongside basic user/password authentication and LDAP.

### Use case

OAuth support in peering-manager makes it easy to support SSO within peering-manager.

### Database changes

Not too sure. I think the OAuth implementation should try to match any user who signs in using OAuth with existing users known to peering-manager via LDAP.

### External dependencies

Perhaps something like this could be used? [https://django-oauth-toolkit.readthedocs.io/en/latest/](https://django-oauth-toolkit.readthedocs.io/en/latest/)

**Comment by Paktosan** [comment]
@gmazoyer I may take a look at it as I am interested in the feature as well.

**Comment by gmazoyer** [comment]
@Paktosan feel free to have a look and ping me if you need any help or insights.
