### ISSUE TITLE
Add "Available Peers" to menu bar

### ISSUE THREAD

**Issue by jlixfeld** [peering-manager/peering-manager#64]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:   3.5.3
* Peering Manager version:   0.99-dev

### Description

Quick access to all available peering sessions across all IXs from Peering Manager menu bar.

**Comment by MrXermon** [comment]
This function would be a really cool feature as we try to setup a as redundant peering as possible to the networks we peer with!
