### ISSUE TITLE
API Calls to /api/peering/routers/{id}/configuration/ using tokenAuth produces HTTP 403

### ISSUE THREAD

**Issue by Nurtic-Vibe** [peering-manager/peering-manager#642]
### Peering Manager version

v1.7.2

### Python version

3.9

### Steps to Reproduce

1. Create User with "Staff" and "Superuser" privileges
2. Create Read/Write Token with the user
3. `curl -X 'GET' 'https://$URL/api/peering/routers/$ID/configuration/' -H 'accept: application/json' -H 'Authorization: $key'`

### Expected Behavior

HTTP Code 202 with scheduled Job
```
  "id": 0,
  "url": "string",
  "created": "2022-10-21T21:34:35.219Z",
  "completed": "2022-10-21T21:34:35.219Z",
  "name": "string",
  "obj_type": "string",
  "status": "pending",
  "user": {
    "id": 0,
    "url": "string",
    "username": "mGPyAlKd9DLM4kyzWqC2dYfQJUdG+HnY1Wos1isdDfb2a5fYHf1R6LqOKlh1J3hTjvg4+_3bpgPwAV+9lrur42hoR6.BKied2fE"
  },
  "data": {
    "additionalProp1": "string",
    "additionalProp2": "string",
    "additionalProp3": "string"
  },
  "job_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "output": "string"
}
```

### Observed Behavior

curl: HTTP 403
docker:
```
peering-manager_1  | Forbidden: /api/peering/routers/2/configuration/
peering-manager_1  | 172.20.0.1 - - [21/Oct/2022:21:36:05 +0000] "GET /api/peering/routers/2/configuration/ HTTP/1.1" 403 0 "-" "curl/7.74.0"
```

**Comment by jamesditrapani** [comment]
The API Authorization header needs to be formatted like so:

```python
Authorization: Token <key>
```

You are missing the `Token` keyword.

**Comment by Nurtic-Vibe** [comment]
The keyword `Token` is then missing in the /api/docs generated CURL request template

**Comment by Nurtic-Vibe** [comment]
See screenshot below
![202210241353](https://user-images.githubusercontent.com/7520183/197519620-0fe66d89-a2f2-42c6-a1a2-9f12e85e6454.png)

**Comment by jamesditrapani** [comment]
Thanks @Nurtic-Vibe, will look to get it fixed up.
