### ISSUE TITLE
CSRF problems are back on EL8

### ISSUE THREAD

**Issue by athompson-merlin** [peering-manager/peering-manager#647]
### Peering Manager version

v1.7.3-dev

### Python version

3.8

### Steps to Reproduce

1. Follow the documentation to install using gunicorn behind nginx proxy on CentOS8/Alma8/RHEL8/etc.
2. start 3 systemd services (peering-manager, peering-manager-rqworker, nginx)
3. try to log in

### Expected Behavior

Should have been able to log in

### Observed Behavior

Similar to what was described in #132 , I get:
```
Forbidden (403)
CSRF verification failed. Request aborted.

More information is available with DEBUG=True.
```

**Comment by athompson-merlin** [comment]
I altered settings.py to dump the assigned value of CSRF_TRUSTED_ORIGINS, like so:
```python
CSRF_TRUSTED_ORIGINS = getattr(configuration, "CSRF_TRUSTED_ORIGINS", [])
print( CSRF_TRUSTED_ORIGINS )
```
and in stdout I get:
`[]`
no matter which way I access the server.

**Comment by athompson-merlin** [comment]
However, if I run the server from `manage.py runserver` then it works fine despite CSRF_TRUSTED_ORIGINS being an empty array?!?
For now I can use the `runserver` approach for testing, but how do I fix this?  Is this an EL8-vs-Ubuntu issue somehow?
(I can send nginx config if that's relevant, opting not to clutter this up until asked.)

**Comment by gmazoyer** [comment]
`CSRF_TRUSTED_ORIGINS` will always be defaulted to an empty array unless you change it yourself in the `configuration.py` file. This is intended behaviour, see [Django docs](https://docs.djangoproject.com/en/4.0/ref/settings/#csrf-trusted-origins) for more details.

**Comment by athompson-merlin** [comment]
OK.  In a way that's too bad, OS-specific problems are sometimes easier to find...

But: since I got out of web development before Django even existed, I have to ask for more guidance on how to resolve this.
My expectation is/was that if there was a mandatory additional step, it would be documented along with the others in [https://peering-manager.readthedocs.io/en/latest/setup/4b-nginx/].
Is this CSRF error something that occurs because I've messed up elsewhere, and just doesn't become visible until I put peering-manager behind nginx?  Or is it environment-specific?  Or is everyone expected to know how to resolve this error on their own?  (And why doesn't it happen in the `runserver` runtime environment, only behind nginx?  Is this an nginx problem?)

VERY confused, and can't tell where to go from here.

**Comment by gmazoyer** [comment]
In general you don't need to modify the `CSRF_TRUSTED_ORIGINS` value but it remains a possibility. Most installs probably did not have to modify it, mine included. Most likely that's a nginx config that triggers the issue, as it looks like you do not face it when bypassing nginx with the built-in web server.
