### ISSUE TITLE
CSS not applying correctly through nginx reverse proxy

### ISSUE THREAD

**Issue by juesor** [peering-manager/peering-manager#661]
### Peering Manager version

v1.4.5

### Python version

3.9

### Steps to Reproduce

Installed Rocky Linux 9.1

Disabled selinux
Installed Setup and started Postgresql-server
Installed glibc-langpack-en and set localectl set-locale LANG=en_US.UTF-8

Created the database & user peering_manager and granted privileges

Setup hg_hba.conf to allow peering_manager user and match on password

Tested psql connectivity with peering_manager 

Installed redis and tested redis-cli ping returned PONG

Installed git
git cloned latest
added user and group peering-manager
granted ownership to peering-manager recursive for /opt/peering-manager

created virtual environment 
upgraded pip
pip3 installed requirements.txt
copied configuration.example.py to configuration.py
modified configuration.py with my SECRET_KEY, TIME_ZONE, NAME, USER, PASSWORD

ran python3 manage.py migrate to import the DB schema

Created admin user 

Collected static files via collectstatic --no-input 

Tested the Application successfully via 
python3 manage.py runserver 0.0.0.0:8000 --insecure

Page loads and looks correct when navigating to http://peeringmanager.xyz.com:8000

Setup gunicorn 
		bind = '127.0.0.1:8001'
		workers = 5
		threads = 3
		timeout = 300
		max_requests = 5000
		max_requests_jitter = 500
		user = 'peering-manager'

created peering-manager.service 
created peering-manager-rqworker.service

installed nginx

added wildcard ssl cert 

setup peeringmanager.conf
server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;

    server_name peeringmanager.xyz.com;

    ssl_certificate /etc/pki/tls/certs/ca.crt;
    ssl_certificate_key /etc/pki/tls/private/ca.key;

    client_max_body_size 25m;

    location / {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header X-Forwarded-Host $server_name;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    # Redirect HTTP traffic to HTTPS
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name peeringmanager.xyz.com;
    return 301 https://$host$request_uri;
}

restarted nginx

tested https://peeringmanager.xyz.com
Page loads but CSS doesn't 

![image](https://user-images.githubusercontent.com/14931420/207165690-ba22098a-7f85-48b4-89cb-cfb24bbf8336.png)

Control-Shift-I shows the following 

Refused to execute script from '<URL>' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
8Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

### Expected Behavior

CSS should apply correctly.

### Observed Behavior

Application looks like dirt.

**Comment by gmazoyer** [comment]
Make sure to add a `location` dedicated to static files that nginx can read. See [documentation ](https://peering-manager.readthedocs.io/en/stable/setup/4b-nginx/) for an example.

**Comment by juesor** [comment]
Thanks for pointing that out i was missing in my peeringmanager.conf for nginx the static delcaration

 location /static/ {
        alias /opt/peeringmanager/static/;
    }
