### ISSUE TITLE
Allow pprint filter, debug extension in Jinja

### ISSUE THREAD

**Issue by athompson-merlin** [peering-manager/peering-manager#674]
### Peering Manager version

1.7.4-dev

### Feature type

New functionality

### Proposed functionality

According to https://jinja.palletsprojects.com/en/2.10.x/templates/#pprint I should be able to dump an entire object by passing it to `| pprint` but that doesn't currently work.

Also, according to https://jinja.palletsprojects.com/en/3.0.x/templates/#debug-statement the `debug` statement now exists... but it's not enabled.

Given that creating new template is the hardest part - by far - of using peering-manager in my environment, I need all the help I can get, and would really like to be able to use these.

### Use case

Eases development of a new template.

### Database changes

n/a

### External dependencies

No new dependencies that I can see.

**Comment by athompson-merlin** [comment]
Looking a little closer, it seems like I ought to be able to add the Jinja2 'debug' extension simply by putting
```python
JINJA2_TEMPLATE_EXTENSIONS = [ 'jinja2.ext.debug' ]
```
in configuration.py, but that does not work.  And I don't know enough Python or Jinja to know why it doesn't work.

**Comment by athompson-merlin** [comment]
To be more clear, at least pprint doesn't die with an exception, but e.g. `{{ local_as | pprint }}` simply produces no output at all, instead of the Python object tree I expected.

**Comment by gmazoyer** [comment]
I've tested it and it appears to work OK. For instance, if I use `{{ local_as | pprint }}` in a template and render the configuration for a particular router I'll get `<AutonomousSystem: AS65400 - The Avengers>` as output.

To add Jinja2 extension, you need to modify the config as you did (restarting the WSGI and rqworker processes is also mandatory for) but you might need to also install the extension packages in Peering Manager virtualenv. In the case of the debug extension, it's shipped with Jinja2 so no extra package is needed.
