### ISSUE TITLE
BGP communities cannot be assigned directly to a peer

### ISSUE THREAD

**Issue by falz** [peering-manager/peering-manager#730]
### Peering Manager version

v1.7.4

### Feature type

Data model extension

### Proposed functionality

In some instances (private peers with) we assign a unique BGP community per peer. These peers are all in the same peer group.

To use netbox, ideally we'd want the ability to assign a community to a peer itsself - right now that does not seem possible.

Currently one can add a bgp community to a peer group, it would be a larger challenge to have all peers in unique groups, which is the only current method we could achieve this.

Perhaps I'm missing something?

### Use case

We use per-peer informational communities that are unique, this is simply an info community. Arbitrary syntax but for example:

1234:301 - Apple (1st peer) in region 3
1234:302 - Google (2nd peer) in region 3
1234:401 - Google (1st peer) in region 4
..

our customers can then see which peer and region the route came from.

**Comment by gmazoyer** [comment]
This is [already supported in the development branch](https://github.com/peering-manager/peering-manager/commit/9e1f214ab02e4fcf437fe8daec2d89e7026a5996) and will be included in the next release.

**Comment by falz** [comment]
Awesome great timing then! effort appreciated
