### ISSUE TITLE
"View Raw" config is still html, not text/plain. This prevents saving web page as txt

### ISSUE THREAD

**Issue by falz** [peering-manager/peering-manager#733]
### Peering Manager version

v1.7.4

### Python version

3.8

### Steps to Reproduce

Go to a device and view configuration. Click 'view raw'. What is displays appears to be plain text.

If however you save the config, it saves it as HTML. The actual text appears to be in a ```<pre>``` tag.

We are using this for debugging purposes when developing templates, saving to text file then loading into a router outside of Peering-manager.

### Expected Behavior

Expected is content type txt and saving the config to a file is actually a text file, not html.

### Observed Behavior

HTML is shown, and not the config, if you save this page.

If ```/routers/X/configuration/?raw``` can be changed to output as MIME type ```text/plain```, this should work as expected.

**Comment by gmazoyer** [comment]
That is indeed weird considering:
https://github.com/peering-manager/peering-manager/blob/daf21847cee811f7e5c5e038d677c42f5e3a4c60/peering/views.py#LL920C41-L920C41

**Comment by falz** [comment]
Is some internal django/bootstrap(?) thing trying to 'be smart' and just wrapping it in HTML on the way out the door?

**Comment by gmazoyer** [comment]
I guess it's not. It's a plain HTTP response that is being returned. Moreover when clicking "View page source" or a button achieving the same goal depending on your browser you'll see that the page code itself contains only the text version of the config with any HTML tags.

So my guess is, that's the browser trying to be clever when hitting CTRL+S (or CMD+S), at least that's what it looks like using Chrome.

**Comment by falz** [comment]
I think you're right, I was using Chrome, just tried Firefox and it didnt do this nonsense. I'll have a few others test to see if it's a chrome thing, or something with my specific extensions.

Sorry for the hassle!

**Comment by gmazoyer** [comment]
Works with other browsers, seems targeted to Chrome (or Chromium) doing inappropriate magic tricks.
