### ISSUE TITLE
Viewing routing policies on peer is confusing - it doesnt display export vs import in view mode

### ISSUE THREAD

**Issue by falz** [peering-manager/peering-manager#737]
### Peering Manager version

v1.7.4

### Python version

3.8

### Steps to Reproduce

1. add routing policies themselves, set some to import, some to export, some to both
2. apply these policies on a bgp group or IX, some as import, some as export
3. when viewing the bgp group or IX, it doesnt separately show you which are applied on import vs export, but it shows you the import/export/both attribute of the policy itsself

See screenshots below, several of my policies could be applied in either direction, such as `Accept`. In view mode it seems like it may be applied in BOTH directions, but in edit mode it confirms it's only applied on import. Same for `RejectSmallPrefixes` and `set-med-100` in these secreenshots

![pm-routing-policies](https://github.com/peering-manager/peering-manager/assets/707319/17d75390-01d4-4d69-b4de-d0348425946c)
![routing-policies-2](https://github.com/peering-manager/peering-manager/assets/707319/13c39773-045e-488d-955e-3b18c7721ece)

### Expected Behavior

I would expect a separated view of what policies are applied in which direction. Without this 

### Observed Behavior

Policies are all lumped together, one can only view what's in which direction in edit view.

**Comment by netravnen** [comment]
Maybe expose the weight metric to? (or something else that shows in which order of precedence the policies of configured to be applied in)... 🤔

**Comment by falz** [comment]
^ Great idea, displaying import/export separately, rendered in order would be extremely helpful

**Comment by netravnen** [comment]
Afaics, The policies are already display in order (export first, then import). Without showing export import separately, it is not necessarily very obvious.

The same with the order the policies are applied in. They are indeed applied in the shown order. (Top to button). It is (again) not necessarily very obvious for me as a user. Unless I specifically look for this. As no number (e.g. numbered list, or the weight) is directly shown alongside the policy name.

---


The example below is export policies (the first two). The following five is the import policies for the BGP Group.

![image](https://github.com/peering-manager/peering-manager/assets/1938389/8d393933-72d5-4d59-b3f3-819dedf2f015)
