### ISSUE TITLE
Rendered Configuration is served via http not https

### ISSUE THREAD

**Issue by jasonyates-thg** [peering-manager/peering-manager#762]
### Peering Manager version

1.8.0

### Python version

3.9

### Steps to Reproduce

Access peering-manager via https URL
Navigate to Devices -> Routers -> <Device> -> Configuration

### Expected Behavior

Rendered configuration is shown

### Observed Behavior

Chrome blocks the request with (blocked:mixed-content)

This is seemingly because peering-manager is serving the dynamic content via a http URL when i'm accessing via https.

**Comment by gmazoyer** [comment]
I cannot reproduce this on my end. It's also working as expected on the demo using HTTPS.

This has been raised a few times here and there and always identified as a missing configuration in the setup. We should address this in the documentation if some bits are missing in it.

**Comment by jasonyates-thg** [comment]
I finally got around to looking at this. My setup has peering-manager behind an L7 Cloudflare Zero Trust proxy with peering-manager's origin configured to listen on HTTP only. I moved my nginx configuration to have the origin served via HTTPS which solved the issue.
