### ISSUE TITLE
Merge error by deploying config is ignored in Webui Configuration Deploymen

### ISSUE THREAD

**Issue by rinsekloek** [peering-manager/peering-manager#784]
### Peering Manager version

1.8.2-dev

### Python version

3.9

### Steps to Reproduce

I'm very happy with Peering manager and I am building a complete Nokia SROS template in combination with two virtual Nokia SR OS V23.3.R3 routers running in Containerlab with 
Hi I am using the Napalm-SROS driver from pip3 package that has been developed by Jvbemmel: https://github.com/napalm-automation-community/napalm-sros:
```
pip3 list | grep napalm
napalm                  4.1.0
napalm-srl              1.0.0
napalm-sros             1.0.0
```

During config deployment when the peering.jobs.set_napalm_configuration() function sends the candidate config to the Nokia SROS router, I do see some inconsistency between the UI and what the Syslog tells about the merge result. I have explained steps below. I would like to see that these merge errors are shown in the UI and also block the deployment of the configuration. 
This is my observation:

Generate config:
```
  Oct 27 09:02:15 peeringmanager python3[754487]: 09:02:15 default: peering.jobs.generate_configuration(<Router: sros01>, job=<Job: da18d6fc-4f44-44e0-920c-7ea03ac3cbd2>) (da18d6fc-4f44-44e0-920c-7ea03ac3cbd2)
  Oct 27 09:02:18 peeringmanager python3[962841]: 09:02:18 default: Job OK (da18d6fc-4f44-44e0-920c-7ea03ac3cbd2)
  Oct 27 09:02:18 peeringmanager python3[962841]: 09:02:18 Result is kept for 500 seconds
```

Deploy config: (With an error in the configuration but no differences in BGP configuration)
```
	Oct 27 09:02:40 peeringmanager python3[754487]: 09:02:40 default: peering.jobs.set_napalm_configuration(<Router: sros01>, False, job=<Job: a3ddca18-bb5f-456c-8aa1-33e71fb665a7>) (a3ddca18-bb5f-456c-8aa1-33e71fb665a7)
	Oct 27 09:03:10 peeringmanager python3[962847]: Merge issue : ('Merge issue: %s', "MINOR: MGMT_CORE #2201: Unknown element - 'Rname'\r")
	Oct 27 09:03:10 peeringmanager python3[962847]: 09:03:10 default: Job OK (a3ddca18-bb5f-456c-8aa1-33e71fb665a7)
	Oct 27 09:03:10 peeringmanager python3[962847]: 09:03:10 Result is kept for 500 seconds
```

    Configuration Deployment WEBUI screen gives `"No configuration differences found."` but Syslog gives:
    Merge issue : `('Merge issue: %s', "MINOR: MGMT_CORE #2201: Unknown element - 'Rname'\r")`
 
 
 
2. With changes in BGP peerings
 
Generate config:
```
	Oct 27 09:06:09 peeringmanager python3[754487]: 09:06:09 default: peering.jobs.generate_configuration(<Router: sros01>, job=<Job: 6fe58a5a-d002-48d3-87ab-fcea3c12430a>) (6fe58a5a-d002-48d3-87ab-fcea3c12430a)
	Oct 27 09:06:12 peeringmanager python3[962953]: 09:06:12 default: Job OK (6fe58a5a-d002-48d3-87ab-fcea3c12430a)
	Oct 27 09:06:12 peeringmanager python3[962953]: 09:06:12 Result is kept for 500 seconds
```

Deploy config: (With an error in the configuration and extra changes in BGP configuration)

```
	Oct 27 09:06:15 peeringmanager python3[754487]: 09:06:15 default: peering.jobs.set_napalm_configuration(<Router: sros01>, False, job=<Job: 36da473e-1dfc-4150-8499-c1d148316f92>) (36da473e-1dfc-4150-8499-c1d148316f92)

	Oct 27 09:06:45 peeringmanager python3[962959]: Merge issue : ('Merge issue: %s', "MINOR: MGMT_CORE #2201: Unknown element - 'Rname'\r")
	Oct 27 09:06:45 peeringmanager python3[962959]: 09:06:45 default: Job OK (36da473e-1dfc-4150-8499-c1d148316f92)
	Oct 27 09:06:45 peeringmanager python3[962959]: 09:06:45 Result is kept for 500 seconds
```

	Configuration differences in Peering Manager onfiguration Deployment screen WebUI:
```
configure {
			router "Base" {
				bgp {
					neighbor "10.0.1.1" {
						prefix-limit ipv4 {
	-                       maximum 1200000
	+                       maximum 120000
						}
					}
					neighbor "2001::1" {
						prefix-limit ipv6 {
	-                       maximum 500000
	+                       maximum 50000
						}
					}
				}
			}
		}
```
		
	But Syslog also says: Merge issue : `('Merge issue: %s', "MINOR: MGMT_CORE #2201: Unknown element - 'Rname'\r")`

Commit config: (With an error in the configuration and extra changes in BGP configuration)
    
	 Peering Manager onfiguration Deployment screen WebUI says Configuration Saved
	
	
```
	Oct 27 09:08:46 peeringmanager python3[754487]: 09:08:46 default: peering.jobs.set_napalm_configuration(<Router: sros01>, True, job=<Job: f059c9e9-7702-4e32-9f98-093c8e6f661a>) (f059c9e9-7702-4e32-9f98-093c8e6f661a)
	Oct 27 09:09:18 peeringmanager python3[962990]: Merge issue : ('Merge issue: %s', "MINOR: MGMT_CORE #2201: Unknown element - 'Rname'\r")
	Oct 27 09:09:18 peeringmanager python3[962990]: 09:09:18 default: Job OK (f059c9e9-7702-4e32-9f98-093c8e6f661a)
	Oct 27 09:09:18 peeringmanager python3[962990]: 09:09:18 Result is kept for 500 seconds
```

### Expected Behavior

Expected behaviour would be that a Merge conflict, including the messages' is show in the UI next to the configuration differences. Also if there is a Merge conflict, the "Save configuration" should be blocked

### Observed Behavior

The Merge confilct error output is only shown in the /var/log/syslog that makes it very confusing why the config is not deployed.

**Comment by rinsekloek** [comment]
Update from my side:

I updated the Napalm_SROS driver to the latest git development version (https://github.com/napalm-automation-community/napalm-sros.git) and It seemd to be fixed now.
This can be closed

**Comment by gmazoyer** [comment]
The best way would be to pin the version of the NAPALM driver inside `local_requirements.txt` and use this file as your own dependency list for your env.
