### ISSUE TITLE
Add Contact Details for Security issues

### ISSUE THREAD

**Issue by Sirius-A** [peering-manager/peering-manager#799]
### Change Type

Addition

### Area

Other - Security

### Proposed Changes

Hey Team

I could not find contact details where one can report potential security issues.

- Where can I report potential security issues, so we can verify them together?
- Would it be possible to document this somewhere (e.g. in a `SECURITY.md`)?

Thanks and BR
Fabio

**Comment by gmazoyer** [comment]
We don't have a way to report security issues indeed apart from contacting me directly. You can find more details about my private contact on [my personal website](https://mazoyer.eu/).

That said thanks for pointing out that we don't have a security policy file as we should have one.

**Comment by gmazoyer** [comment]
Security policy and how to report a vulnerability has been added (see [this special repo)](https://github.com/peering-manager/.github).
