### ISSUE TITLE
PeeringDB sync not working?

### ISSUE THREAD

**Issue by ianbarrere** [peering-manager/peering-manager#833]
### Peering Manager version

v1.8.3

### Python version

3.9

### Steps to Reproduce

Any attempt to synchronize with PeeringDB doesn't seem to work. I have tried via the API call towards api/peeringdb/cache/update-local/, I have tried the CLI command venv/bin/python3 manage.py peeringdb_sync, and I've also tried clicking "Synchronise" in the AS I'm interested in (36062 at the moment). I recently updated the max IPv4 prefixes from 7 to 10 for ASN 36062 in PeeringDB, and querying PeeringDB directly returns the updated prefix value, but this value does not seem to make it to PeeringManager.

I have looked at the job report in api/core/jobs/{job-id}/ and I see that something was updated:

```                [
                    "2024-04-11T22:50:03.777119+00:00",
                    "info",
                    null,
                    null,
                    "Updated 2 objects"
                ],
```

Is it possible to see what was updated from this job?

It's possible that I may not be waiting long enough either. I'm not sure how fast these changes usually take effect, but it has been less than an hour so far.

This was all in an attempt to test if automated synchronization updates from PeeringDB trigger webhooks, which you may be able to answer easier separately. I have built some automation around our peering config I wanted to make sure that for example, if one of our peer ASes updates their max prefixes in PeeringDB that a webhook will be triggered from PeeringManager as though the max prefix was updated directly in PeeringManager.

### Expected Behavior

I would expect that the properties synchronize from PeeringDB.

### Observed Behavior

The properties have not been synchronized from PeeringDB.

**Comment by gmazoyer** [comment]
PeeringDB synchronisation still works at the moment. This can be verified using the [demo instance](https://demo.peering-manager.net/api/peeringdb/networks/?asn=36062).

However when you update a value in PeeringDB record, while the value will be immediately available if you query a detail view of said record, it will take some time to get to the global list view which is provided via PeeringDB's API. These global list views return cached data. Peering Manager uses these views, hence an update to a record not being propagated immediately.

**Comment by ianbarrere** [comment]
Hmm, interesting. So it appears to be an issue with just my installation at least. It has now been around 18 hours but the update is still not reflected in my instance:

<img width="608" alt="Screenshot 2024-04-12 at 11 38 20" src="https://github.com/peering-manager/peering-manager/assets/112948556/91eba640-3a82-4daf-b661-c6df2605409d">

I have run the sync several more times since then as well.

Is somewhere I can check internally to see where it might be going wrong?

**Comment by gmazoyer** [comment]
You might be facing a de-sync due to the multiple sync processes you tried running (known issue, hard to solve). That said, the sync process is self healing if you start it from scratch.

I'd recommend you to run `venv/bin/python3 manage.py peeringdb_sync --flush` which will clear out the local cache and then `venv/bin/python3 manage.py peeringdb_sync` which will re-populate it. After that you should have the correct values set.

As a side note, like mention there is a known issue with data de-sync / data drift when running the sync process over time. So I also recommend to flush and sync from scratch from time to time to ensure you have all the data locally.

**Comment by ianbarrere** [comment]
Strange... I ran the commands you suggested and indeed it seemed to do a lot more work than it had been doing before, it took quite some time to sync which I assumed would fix the problem, but it's still reporting as 7 (through the web UI, API, everywhere that I can query basically). I wonder if it has to do with 36062 being marked as affiliated for me? In any case I also tried unchecking affiliated, attempting another sync, and rechecking, which also did not work. Any other ideas?

**Comment by gmazoyer** [comment]
Use the same path (`/api/peeringdb/networks/?asn=36062`) to your local Peering Manager instance as the one I linked with the demo. It'll show if the data in the cache is locally correct.

Make sure you use [an API with PeeringDB](https://docs.peering-manager.net/configuration/tools/#peeringdb_api_key) to avoid hitting the enforced rate limit, otherwise you won't be able to retrieve all data.

Marking an AS as affiliated won't change anything except on the "PeeringDB" tab of the AS view where, if you change something, you will have a button to push data to PeeringDB.

**Comment by ianbarrere** [comment]
Oh, interesting! OK, yeah I was looking at `api/peering/autonomous-systems/?asn=36062`, which shows 7, but the endpoint you listed `/api/peeringdb/networks/?asn=36062` shows the correct value of 10. So I guess my next question is if values like max prefixes fetched from PeeringDB are meant to automatically propagate to the data structures at, for example, `api/peering/autonomous-systems`?

Also good point about the API key, I was not using one before, so I will add that, however it seems that the sync worked properly since it has the correct value at `/api/peeringdb/networks/?asn=36062`.

Thanks for your help here, and this is a great tool by the way, I'm looking forward to getting it into production.

**Comment by gmazoyer** [comment]
As long as you have the right boxes checked in the "Synchronise with PeeringDB (if public AS)" section of the AS form, values for the corresponding fields should be replicated automatically when running the `peeringdb_sync` command (I just noticed that the async job does not do that, this needs to be fixed).

**Comment by ianbarrere** [comment]
> As long as you have the right boxes checked in the "Synchronise with PeeringDB (if public AS)" section of the AS form

That was it 🤦 

I didn't even see those options since I had added the ASes through the API. I see now that the API schema also has them, so I will make sure that's enabled for those that I add. Should be good now!
