### ISSUE TITLE
Bulk edits of status removes routing policies from ASNs and IX sessions

### ISSUE THREAD

**Issue by lucasalvatore** [peering-manager/peering-manager#850]
### Peering Manager version

v1.8.3

### Python version

3.10

### Steps to Reproduce

1. Select multiple things such as ASNs or IX peering sessions and click "edit selected"
2. Change their status to something else, e.g."Maintenance"
3. Click Apply

### Expected Behavior

Only the status should be changed

### Observed Behavior

Any import or export policy that was assigned is now removed.

**Comment by gmazoyer** [comment]
I think that this issue is the same as https://github.com/peering-manager/peering-manager/issues/840, which has been fixed in https://github.com/peering-manager/peering-manager/commit/dec3e16c3bb587c80796918bc4e88d343f207636.

**Comment by lucasalvatore** [comment]
Ah, thank you.  I mad the change mentioned above and it did indeed fix this issue. I'll close this out
