### ISSUE TITLE
templating error

### ISSUE THREAD

**Issue by kieber** [peering-manager/peering-manager#859]
### Peering Manager version

v1.9.0-dev

### Python version

3.12

### Steps to Reproduce

1. Using the peering request mail template at https://peering-manager.readthedocs.io/en/stable/templating/examples/peering-request-email/ create a template at Messaging ->E-mails
2. Go to Provisioning -> Send E-mail To Network and try using that template to send an email to a prospective peer

### Expected Behavior

A peering request as per template.

### Observed Behavior

  File "/opt/peering-manager/peering_manager/jinja2/filters.py", line 280, in get
    if q.count() == 1:
       ^^^^^^^^^
TypeError: list.count() takes exactly one argument (0 given)

**Comment by gmazoyer** [comment]
The mentioned template cannot be used in this context. You'll have to use one such as [this one](https://peering-manager.readthedocs.io/en/stable/templating/examples/new-network-email/).

The beginning of the doc page provides a bit of context, but it might be worth to move it somewhere else until we find a way to make e-mail template less counter intuitive.
