### ISSUE TITLE
Arbitrary variables support

### ISSUE THREAD

**Issue by jlixfeld** [peering-manager/peering-manager#97]
### Environment
* Python version:  3.5.3
* Peering Manager version:  master

### Proposed Functionality

- Support for various types of arbitrary variables:
-- community type
-- integer type
-- string type
-- etc..

- To be efficient with screen realestate, potentially move community and routing policy under the "Variables" umbrella.  ie:  A `Routing Policies` entry now be a policy type variable.  A `Communities` entry would become community type variable.

### Use Case

IOS-XR supports variables when mapping route-policy to BGP sessions:
```
!
router bgp 2
 vrf foo
  neighbor 198.32.160.1
   remote-as 13538
   use neighbor-group IXP:NYIIX:V4
   description "AS13538 - NYIIX Route Servers"
   enforce-first-as disable
   address-family ipv4 unicast
    send-community-ebgp
    maximum-prefix 37000 100 restart 60
    route-policy RS:NYIIX:OUT(2030, 65535, 666) out
   !
  !
 !
!
route-policy RS:NYIIX:OUT($IXP, $RTBH_ASN, $RTBH_ID)
  apply GLOBAL:FILTER
  apply GLOBAL:ANNOUNCE:OUT
  apply GLOBAL:RTBH($RTBH_ASN, $RTBH_ID)
  apply GLOBAL:DROP(2000, $IXP)
  # 02/06/19 - jlixfeld: Move fill to Seattle
  set community (0:2906) additive
  done
end-policy
!
```

Allowing arbitrary variables could allow a routing policy to be constructed on a session using different defined variables, or even free-hand.

See very rudimentary visual representation attached.

![pastedgraphic-4](https://user-images.githubusercontent.com/17339017/52427424-de6f2900-2acd-11e9-83a7-8a98ea5d903b.png)

**Comment by respawner** [comment]
Maybe we could add some kind of `configuration_context` field that could be then used in templating (just an idea I had, that needed to be written not to be forgotten).

**Comment by jnikoletich** [comment]
I think this would be a good option to have. Would also setup to prep for generation of routing policies by peering-manager.

**Comment by ggiesen** [comment]
I'd love to see this as well, as I have per-peer routing policies that reference their ASN, but I don't want to configure Peering Manager with all the individual policy names for each peer (and have to assign them on a per-peer basis as well)

**Comment by gmazoyer** [comment]
I'd like to know if you feel this is addressed in 7f4e1f5 or if we need to go further to close the issue.

**Comment by jamesditrapani** [comment]
This ties into #505, happy to have some feedback in that thread!

**Comment by gmazoyer** [comment]
Closing it as it seems resolved.
